### ISSUE TITLE
As a user I want my own navigational service of choice, such as google maps or some other application, to open when I want directions on how to get to the facility.

### ISSUE THREAD

**Issue by rkalantari7** [Dialoc/dialoc#32]
Scenario 1: In my settings, I choose what navigation system I want to use.
Given I have the app downloaded.
	When I want to use my own specified navigational service to get to the clinic
	Then I will have an experience catered to me.
	b. Scenario 2: The system automatically uses the phones provided navigation service
Given I have not set my specified navigational service.
	When I want to get to a clinic through the app.
	Then I will get there using the service provided by my phone

**Comment by tlilly3** [comment]
I don't think this is needed. The app should use system defaults or prompt system menu
