### ISSUE TITLE
As a user I would like to be able to set the UI of the application to suit my abilities, in the case of auditory or visual impairment.

### ISSUE THREAD

**Issue by rkalantari7** [Dialoc/dialoc#36]
Scenario 1: I want to update the UI to better suit my medical needs to enable better access and consumption of media and information
Given I have some auditory or visual impairment
	When I have the app open
	Then The app will go into accessibility mode and alter its layout including but not limited to font, color, and such to suit your needs

**Comment by tlilly3** [comment]
We need to more concretely define this issue
